In [1]:
import numpy as np
from units import *
from quantity import *
from refsys import *
from objects import *

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
d = DimensionStructure(up={"mass":1, "space":-1, "time":-2})
d0 = DimensionStructure(up={"mass":1, "space":-1, "time":-2})
print(d==d0)
print(d-d0)
print(d*2)
print(d*d0)
print(d/d0)
print(d**1.5)

std = ComplexUnit(dim=d0, basic_unit_map={"space":meter, "time":second, "mass": kilogram})
spec = ComplexUnit(dim=d0, basic_unit_map={"space":kilometer, "time":minute, "mass": gram})
print(spec.unitToStd(1))
print(meter, spec)
print(meter/kilogram)

True
{'mass': 1, 'space': -1, 'time': -2}
{'mass': 1, 'space': -1, 'time': -2}
{'mass': 2, 'space': -2, 'time': -4}
{'mass': 0, 'space': 0, 'time': 0}
{'mass': 1.5, 'space': -1.5, 'time': -3.0}
2.7777777777777777e-10
[m] [g km^-1 min^-2 ]
[m kg^-1 ]


In [3]:
l = Quantity(value=np.array([1.2, 3, 7.5]), unit=kilometer)
t = Quantity(value=np.float64(5), unit=minute)
print(l/t)
l.setUnit(meter)
t.setUnit(second)
print(l/t)
v = l/t
kmmin = ComplexUnit(dim=v.unit.dim, basic_unit_map={"space":kilometer, "time":minute})
v.setUnit(kmmin)
print(v)
print(v**2/l)

[0.24 0.6  1.5 ] [km min^-1 ]
[ 4. 10. 25.] [m s^-1 ]
[0.24 0.6  1.5 ] [km min^-1 ]
[0.048 0.12  0.3  ] [km min^-2 ]


In [7]:
m1 = Mass(23.3, kilogram)
m2 = Mass(603, gram)
print(m1 + m2)

pos1 = Position(2.2, 3.2, 8.3, meter)
pos2 = Position(3.1, 5.7, 2.345, meter)
print(pos1 * pos2)
print(pos2.getAbsValue())

min1 = MinkowskiEvent(2.2, 3.2, 1, 1.2)
print(min1)
print(min1.getAbsValue())

23.903000000000002 [kg]
[ 6.82   18.24   19.4635] [m^2 ]
6.899204664307329 [m]
[2.2+0.0e+00j 3.2+0.0e+00j 1. +0.0e+00j 0. +3.6e+08j] [m]
(2.204364238465235e-08+359999999.9999999j) [m]


In [5]:
obj1 = DynamicObject()
print(obj1)

mass: 1e-20 [kg]
position: [0. 0. 0.] [m]
velocity: [0. 0. 0.] [m s^-1 ]
force: [0. 0. 0.] [m s^-2 kg ]


In [6]:
refsys = ReferenceSystem(axis_x=Position(0, 1, 0), axis_y=Position(1, 0, 0), axis_z=Position(0, 0, 1))
print(refsys.stdToRef(Position(2, 4, 1)))
print(refsys.refToStd(Position(4, 2, 1)))

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[4. 2. 1.] [m]
[2. 4. 1.] [m]
